### ISSUE TITLE
Drawing the outline of an rectangle?

### ISSUE THREAD

**Issue by Selur** [kewenyu/VapourSynth-Draw#2]
Could this be used to draw the outline of a rectangle?
I would like have some sort of 'show'-mode for the crop option, for which I would need to draw the outline of a rectangle on the frame (instead of cropping it). Any idea  whether:
a. Vapoursynth-Draw could be used for this
b.  How the expression would need to look like to do this?

**Comment by kewenyu** [comment]
Yes, you can.

There is already an example in README.md showing how to draw a rectangle:
```Python
# Draw a white rectangle on Y plane and set UV to 128
rect = core.draw.Draw(src, ['x 960 - abs 100 < y 540 - abs 50 < and 255 0 ?', '128'])
```

You can simply subtract a small rectangle from a large one if you want the "outline" part of the rectangle only:
```Python
# Outline of 6 pixels
big_rect = core.draw.Draw(src, ['x 960 - abs 100 < y 540 - abs 50 < and 255 0 ?', '128'])
small_rect = core.draw.Draw(src, ['x 960 - abs 94 < y 540 - abs 44 < and 255 0 ?', '128'])
outline = core.std.Expr([big_rect, small_rect], ['y 254 > 0 x ?', '128'], vs.YUV)
```

Note that in above examples the src is assumed to be a YUV420P8 clip with resolution of 1920x1080. The 960 and 540 are the x, y of the rectangle's central point respectively. You can use left-upper corner point (which I believe is more convenient in your "crop" scenario) or even combine the expression so that you can save a extra step of subtraction but in that way you need to figure out the expression by yourself.

**Comment by Selur** [comment]
Thanks. :)
